---
apiVersion: v1 #DRISSI Anasse  RENOUT Quentin
kind: ServiceAccount
metadata:
  name: service1-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-only-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"] # Ce rôle ne peut que lire la liste des pods, rien d'autre
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-only-binding
subjects:
- kind: ServiceAccount
  name: service1-account
roleRef:
  kind: Role
  name: read-only-role
  apiGroup: rbac.authorization.k8s.io